/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Facades.Fac_Articulos;
import Facades.Fac_Marcas;
import Facades.Fac_Rubros;
import Templates.DialogoConsulta;
import Templates.QueryGral;
import entidades.Articulos;
import entidades.Marcas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author smuser
 */
public class V_Articulos extends javax.swing.JDialog {

    int opcion = 0;
    Articulos objArticulo = new Articulos();
    Fac_Articulos facArti = new Fac_Articulos();

    public V_Articulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TMarca_id = new javax.swing.JTextField();
        BBuscarMarca = new javax.swing.JButton();
        LMarca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TRubro_id = new javax.swing.JTextField();
        BBuscarRubro = new javax.swing.JButton();
        LRubro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TArticulo_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TArticuloDes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TCadBarra = new javax.swing.JTextField();
        TPrecio = new javax.swing.JFormattedTextField();
        TCantidad = new javax.swing.JFormattedTextField();
        BBBuscarArticulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BNuevo = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Marca id");

        TMarca_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TMarca_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TMarca_idKeyPressed(evt);
            }
        });

        BBuscarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        BBuscarMarca.setAlignmentY(0.0F);
        BBuscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarMarcaActionPerformed(evt);
            }
        });

        LMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LMarca.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rubro");

        TRubro_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TRubro_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TRubro_idKeyPressed(evt);
            }
        });

        BBuscarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        BBuscarRubro.setAlignmentY(0.0F);
        BBuscarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarRubroActionPerformed(evt);
            }
        });

        LRubro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LRubro.setText("Rubro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        TArticulo_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TArticulo_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TArticulo_idKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Artículo");

        TArticuloDes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TArticuloDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TArticuloDesKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Código Barra");

        TCadBarra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TCadBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCadBarraKeyPressed(evt);
            }
        });

        TPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        TPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BBBuscarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        BBBuscarArticulo.setAlignmentY(0.0F);
        BBBuscarArticulo.setEnabled(false);
        BBBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBBuscarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TArticuloDes, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(TPrecio, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TArticulo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BBBuscarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TRubro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BBuscarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LRubro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TMarca_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BBuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 42, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TCadBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TArticulo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(BBBuscarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TArticuloDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TMarca_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(LMarca)))
                    .addComponent(BBuscarMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LRubro))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BBuscarRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TRubro_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TCadBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BNuevo.setText("Nuevo");
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BEditar.setText("Editar");
        BEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarActionPerformed(evt);
            }
        });

        BConsultar.setText("Consultar");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        BAceptar.setText("Aceptar");
        BAceptar.setEnabled(false);
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });

        BCancelar.setText("Cancelar");
        BCancelar.setEnabled(false);
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(BEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        opcion = 1;
        BNuevo.setEnabled(false);
        BEditar.setEnabled(false);
        BConsultar.setEnabled(false);

        BAceptar.setEnabled(true);
        BCancelar.setEnabled(true);
        TArticulo_id.setEnabled(false);
        BBBuscarArticulo.setEnabled(false);
        BBuscarMarca.setEnabled(true);
        BBuscarRubro.setEnabled(true);

        TArticuloDes.requestFocusInWindow();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarActionPerformed
        opcion = 2;
        BNuevo.setEnabled(false);
        BEditar.setEnabled(false);
        BConsultar.setEnabled(false);

        BAceptar.setEnabled(true);
        BCancelar.setEnabled(true);
        TArticulo_id.setEnabled(true);
        BBBuscarArticulo.setEnabled(true);
        BBuscarMarca.setEnabled(true);
        BBuscarRubro.setEnabled(true);

        TArticulo_id.requestFocusInWindow();
    }//GEN-LAST:event_BEditarActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        opcion = 3;
        BNuevo.setEnabled(false);
        BEditar.setEnabled(false);
        BConsultar.setEnabled(false);

        BAceptar.setEnabled(true);
        TArticulo_id.setEnabled(true);
        BBBuscarArticulo.setEnabled(true);
        BBuscarMarca.setEnabled(false);
        BBuscarRubro.setEnabled(false);

        BCancelar.setEnabled(true);
    }//GEN-LAST:event_BConsultarActionPerformed

    private void LimpiarObjetos() {
        TArticuloDes.setText("");
        TArticulo_id.setText("");
        TCantidad.setText("");
        TPrecio.setText("");
        TCadBarra.setText("");
        LMarca.setText("");
        TMarca_id.setText("");
        LRubro.setText("");
        TRubro_id.setText("");
    }

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        if (opcion == 1) { // para grabar
            if (JOptionPane.showConfirmDialog(this, "Esta Seguro de Registrar Nuevo Artículo", "Atención", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                if (TArticuloDes.getText().length() <= 2) {
                    JOptionPane.showMessageDialog(this, "Nombre de Artículo Incorrecto", " Información", JOptionPane.ERROR_MESSAGE);
                    TArticuloDes.requestFocusInWindow();
                    return;
                }

                if (facArti.Existe_Articulo_Des(TArticuloDes.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Ya Existe Artículo " + TArticuloDes.getText(), " Información", JOptionPane.ERROR_MESSAGE);
                    TArticuloDes.requestFocusInWindow();
                    return;
                }
                if (TCantidad.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Cantidad ", " Información", JOptionPane.ERROR_MESSAGE);
                    TCantidad.requestFocusInWindow();
                    return;
                }

                if (TPrecio.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Precio ", " Información", JOptionPane.ERROR_MESSAGE);
                    TPrecio.requestFocusInWindow();
                    return;
                }

                if (TMarca_id.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Marca ", " Información", JOptionPane.ERROR_MESSAGE);
                    TMarca_id.requestFocusInWindow();
                    return;
                }

                if (TRubro_id.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Rubro ", " Información", JOptionPane.ERROR_MESSAGE);
                    TRubro_id.requestFocusInWindow();
                    return;
                }
                objArticulo.setArticulo(TArticuloDes.getText().trim());
                objArticulo.setCantidad(Integer.parseInt(TCantidad.getText()));
                objArticulo.setCodigobarra(TCadBarra.getText().trim());
                objArticulo.setMarca_id(Integer.parseInt(TMarca_id.getText()));
                objArticulo.setRubro_id(Integer.valueOf(TRubro_id.getText()));
                objArticulo.setPrecio(Float.valueOf(TPrecio.getText()));
                try {
                    facArti.Nuevo_Articulo(objArticulo);
                } catch (SQLException ex) {
                    Logger.getLogger(V_Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Artículo Registrado con exito", " Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        if (opcion == 2) {
            if (JOptionPane.showConfirmDialog(this, "Esta Seguro de Editar la Marca", "Atención", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (TArticuloDes.getText().length() <= 2) {
                    JOptionPane.showMessageDialog(this, "Nombre de Artículo Incorrecto", " Información", JOptionPane.ERROR_MESSAGE);
                    TArticuloDes.requestFocusInWindow();
                    return;
                }

                if (facArti.Existe_Articulo_Des(TArticuloDes.getText())) {
                    JOptionPane.showMessageDialog(this, "Ya Existe Artículo " + TArticuloDes.getText(), " Información", JOptionPane.ERROR_MESSAGE);
                    TArticuloDes.requestFocusInWindow();
                    return;
                }
                if (TCantidad.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Cantidad ", " Información", JOptionPane.ERROR_MESSAGE);
                    TCantidad.requestFocusInWindow();
                    return;
                }

                if (TPrecio.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Precio ", " Información", JOptionPane.ERROR_MESSAGE);
                    TPrecio.requestFocusInWindow();
                    return;
                }

                if (TMarca_id.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Marca ", " Información", JOptionPane.ERROR_MESSAGE);
                    TMarca_id.requestFocusInWindow();
                    return;
                }

                if (TRubro_id.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No definio Rubro ", " Información", JOptionPane.ERROR_MESSAGE);
                    TRubro_id.requestFocusInWindow();
                    return;
                }

                objArticulo.setArticulo(TArticuloDes.getText().trim());
                objArticulo.setCantidad(Integer.parseInt(TCantidad.getText()));
                objArticulo.setCodigobarra(TCadBarra.getText().trim());
                objArticulo.setMarca_id(Integer.parseInt(TMarca_id.getText()));
                objArticulo.setRubro_id(Integer.valueOf(TRubro_id.getText()));
                objArticulo.setPrecio(Float.valueOf(TPrecio.getText()));
                try {
                    facArti.Editar_Articulos(objArticulo);
                } catch (SQLException ex) {
                    Logger.getLogger(V_Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Artículo Registrado con exito", " Información", JOptionPane.INFORMATION_MESSAGE);
                LimpiarObjetos();
                return;
            }
        }
        if (opcion == 3) { // consulta
            BBuscarMarca.setEnabled(true);
            TMarca_id.setEnabled(true);
            TMarca_id.requestFocusInWindow();
        }

    }//GEN-LAST:event_BAceptarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        opcion = 0;
        BNuevo.setEnabled(true);
        BEditar.setEnabled(true);
        BConsultar.setEnabled(true);

        BAceptar.setEnabled(false);
        BCancelar.setEnabled(false);
        BBuscarMarca.setEnabled(false);
        BBuscarRubro.setEnabled(false);

        BSalir.requestFocusInWindow();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void TMarca_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TMarca_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMarca_idKeyPressed

    private void BBuscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarMarcaActionPerformed
        int pMarca_id = -1;
        QueryGral QGP = new QueryGral("marcas", "marca_id", "marca", "");
        QGP.setColumName1("ID");
        QGP.setColumName2("Marcas");

        DialogoConsulta DialogConsul = new DialogoConsulta(null, rootPaneCheckingEnabled);
        DialogConsul.setTitle("Buscar Marcas");
        DialogConsul.setVisible(true);
        if (!QGP.getValor_des().isEmpty()) {
            LMarca.setText(QGP.getValor_des());
            pMarca_id = Integer.parseInt(QGP.getValor_id());
            TMarca_id.setText(String.valueOf(pMarca_id));
        } else {
            LMarca.setText("");
            TMarca_id.setText("");
        }
    }//GEN-LAST:event_BBuscarMarcaActionPerformed


    private void TRubro_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TRubro_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRubro_idKeyPressed

    private void BBuscarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarRubroActionPerformed

        QueryGral QGP = new QueryGral("rubros", "rubro_id", "rubro", "");
        QGP.setColumName1("ID");
        QGP.setColumName2("Rubros");

        DialogoConsulta DialogConsul = new DialogoConsulta(null, rootPaneCheckingEnabled);
        DialogConsul.setTitle("Buscar Rubros");
        DialogConsul.setVisible(true);
        if (!QGP.getValor_des().isEmpty()) {
            LRubro.setText(QGP.getValor_des());
            TRubro_id.setText(String.valueOf(Integer.parseInt(QGP.getValor_id())));
        } else {
            LRubro.setText("");
            TRubro_id.setText("");
        }
    }//GEN-LAST:event_BBuscarRubroActionPerformed

    private void TArticulo_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TArticulo_idKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TArticulo_idKeyPressed

    private void TArticuloDesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TArticuloDesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TArticuloDesKeyPressed

    private void TCadBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCadBarraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCadBarraKeyPressed

    private void BBBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBBuscarArticuloActionPerformed
        int pArticulo_id;
        QueryGral QGP = new QueryGral("articulos", "articulo_id", "articulo", "");
        QGP.setColumName1("ID");
        QGP.setColumName2("Articulos");

        DialogoConsulta DialogConsul = new DialogoConsulta(null, rootPaneCheckingEnabled);
        DialogConsul.setTitle("Buscar Articulos");
        DialogConsul.setVisible(true);
        if (!QGP.getValor_des().isEmpty()) {
            TArticuloDes.setText(QGP.getValor_des());
            pArticulo_id = Integer.parseInt(QGP.getValor_id());
            try {
                objArticulo = facArti.ObtenerArticulos(pArticulo_id);
                TArticulo_id.setText(String.valueOf(objArticulo.getArticulo_id()));
                TPrecio.setText(String.valueOf(objArticulo.getPrecio()));
                TCantidad.setText(String.valueOf(objArticulo.getCantidad()));
                TCadBarra.setText(objArticulo.getCodigobarra());
                Fac_Marcas facMarca = new Fac_Marcas();
                TMarca_id.setText(String.valueOf(objArticulo.getMarca_id()));
                LMarca.setText(facMarca.ExisteMarca_Id(objArticulo.getMarca_id()));
                Fac_Rubros facRubro = new Fac_Rubros();
                TRubro_id.setText(String.valueOf(objArticulo.getRubro_id()));
                LRubro.setText(facRubro.ExisteRubro_Id(objArticulo.getRubro_id()));

            } catch (SQLException ex) {
                Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            objArticulo.setArticulo_id(-1);
            //Limpiar();
        }        // TODO add your handling code here:

    }//GEN-LAST:event_BBBuscarArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_Articulos dialog = new V_Articulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BBBuscarArticulo;
    private javax.swing.JButton BBuscarMarca;
    private javax.swing.JButton BBuscarRubro;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LRubro;
    private javax.swing.JTextField TArticuloDes;
    private javax.swing.JTextField TArticulo_id;
    private javax.swing.JTextField TCadBarra;
    private javax.swing.JFormattedTextField TCantidad;
    private javax.swing.JTextField TMarca_id;
    private javax.swing.JFormattedTextField TPrecio;
    private javax.swing.JTextField TRubro_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
