/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Facades.Fac_Articulos;
import Facades.Fac_Marcas;
import Facades.Fac_Rubros;
import Facades.Fac_TmpVentasR;
import Templates.DialogoConsulta;
import Templates.QueryGral;
import entidades.Articulos;
import entidades.Conexion;
import entidades.Marcas;
import entidades.Rubros;
import entidades.Tmp_VentasR;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class V_Ventas extends javax.swing.JDialog {

    Articulos ObjArticulo = new Articulos();
    Fac_Articulos facArticulo = new Fac_Articulos();

    Marcas objMarca = new Marcas();
    Fac_Marcas fMarca = new Fac_Marcas();

    Rubros objRubro = new Rubros();
    Fac_Rubros facRubros = new Fac_Rubros();

    Tmp_VentasR ObjTmpVentaR = new Tmp_VentasR();
    Fac_TmpVentasR facTVentasR = new Fac_TmpVentasR();

    /**
     * Creates new form V_Ventas
     */
    public V_Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargarTablaDetalles();
        LTotal.setText(String.valueOf( facTVentasR.getTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LArticulo = new javax.swing.JLabel();
        TCodBarra = new javax.swing.JTextField();
        BBArticulo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LDisponible = new javax.swing.JLabel();
        BAgregar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaDetalle = new javax.swing.JTable();
        TCantidad = new javax.swing.JFormattedTextField();
        LMarca = new javax.swing.JLabel();
        LRubro = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LSubTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BConfirmar = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cliente");

        TCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LArticulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LArticulo.setText("Articulo");

        TCodBarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCodBarraActionPerformed(evt);
            }
        });
        TCodBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCodBarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCodBarraKeyTyped(evt);
            }
        });

        BBArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        BBArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBArticuloActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Articulo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Precio");

        TPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("SubTotal   $");

        LDisponible.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LDisponible.setForeground(new java.awt.Color(102, 102, 255));
        LDisponible.setText("0.00");

        BAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/check2.png"))); // NOI18N
        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        BAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BAgregarKeyPressed(evt);
            }
        });

        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/process-stop.png"))); // NOI18N
        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        JTablaDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 255), new java.awt.Color(51, 204, 0)));
        JTablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTablaDetalle);

        TCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCantidadKeyTyped(evt);
            }
        });

        LMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LMarca.setText("Marca");

        LRubro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LRubro.setText("Rubro");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Disponible: ");

        LSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LSubTotal.setForeground(new java.awt.Color(102, 102, 255));
        LSubTotal.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Marca:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rubro:");

        LTotal.setBackground(new java.awt.Color(0, 255, 255));
        LTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LTotal.setForeground(new java.awt.Color(0, 153, 51));
        LTotal.setText("0.00");
        LTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(7, 7, 7)
                                .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(LSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(BBArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(LMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(LTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(LArticulo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BBArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LMarca)
                        .addComponent(LRubro)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LSubTotal))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(LDisponible)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(BAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/_nuevo24.png"))); // NOI18N
        BConfirmar.setText("Confirmar");
        BConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmarActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBArticuloActionPerformed
        int pArticulo_id;
        QueryGral QGP = new QueryGral("articulos", "articulo_id", "articulo", "");
        QGP.setColumName1("ID");
        QGP.setColumName2("Articulos");

        DialogoConsulta DialogConsul = new DialogoConsulta(null, rootPaneCheckingEnabled);
        DialogConsul.setTitle("Buscar Articulos");
        DialogConsul.setVisible(true);
        if (!QGP.getValor_des().isEmpty()) {
            LArticulo.setText(QGP.getValor_des());
            pArticulo_id = Integer.parseInt(QGP.getValor_id());
            try {
                ObjArticulo = facArticulo.ObtenerArticulos(pArticulo_id);
                TPrecio.setText(String.valueOf(ObjArticulo.getPrecio()));
                TCodBarra.setText(ObjArticulo.getCodigobarra());
                LMarca.setText(fMarca.ExisteMarca_Id(ObjArticulo.getMarca_id()));
                LRubro.setText(facRubros.ExisteRubro_Id(ObjArticulo.getRubro_id()));
                LDisponible.setText(String.valueOf(ObjArticulo.getCantidad()));
                //  TCantidad.setText("1");
                TCantidad.requestFocusInWindow();
            } catch (SQLException ex) {
                Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ObjArticulo.setArticulo_id(-1);
            //Limpiar();
        }
    }//GEN-LAST:event_BBArticuloActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        try {
            int art_id = Integer.parseInt(JTablaDetalle.getValueAt(JTablaDetalle.getSelectedRow(), 0).toString());
            facTVentasR.Eliminar_Tmp_VentasR(art_id);
            CargarTablaDetalles();
            LTotal.setText(String.valueOf( facTVentasR.getTotal()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Artículo ", " Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void LimpiarArticulo() {
        TCodBarra.setText("");
        LArticulo.setText("____");
        TPrecio.setText("");
        TCantidad.setText("0");
        LMarca.setText("");
        LRubro.setText("");
        LSubTotal.setText("0.00");
        LDisponible.setText("0");
        ObjArticulo.setArticulo_id(-1);
        TCodBarra.requestFocusInWindow();

    }
    
    
    private void AgregarRegistro()
    {
        try {
            if (ObjArticulo.getArticulo_id() == -1) {
                JOptionPane.showMessageDialog(this, " No Selecciono Articulo", " Información", JOptionPane.ERROR_MESSAGE);
                TCantidad.requestFocusInWindow();
                return;
            }

            if (TCantidad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "NO ingreso Cantidad ", "Información", JOptionPane.ERROR_MESSAGE);
                TCantidad.requestFocusInWindow();
                return;
            }

            if (ObjArticulo.getCantidad() < Integer.valueOf(TCantidad.getText())) {
                JOptionPane.showMessageDialog(this, "Cantidad No Disponible \nSolo Dispone de " + ObjArticulo.getCantidad(), " Información", JOptionPane.ERROR_MESSAGE);
                TCantidad.requestFocusInWindow();
                return;
            }
            if (facTVentasR.Existe_Articulo_Id(ObjArticulo.getArticulo_id())) {
                JOptionPane.showMessageDialog(this, "Ya Cargo Artículo " + ObjArticulo.getArticulo(), " Información", JOptionPane.ERROR_MESSAGE);
                TCantidad.requestFocusInWindow();
                return;
            }

            ObjTmpVentaR.setArticulo(ObjArticulo.getArticulo()+" "+LMarca.getText());
            ObjTmpVentaR.setArticulos_id(ObjArticulo.getArticulo_id());
            ObjTmpVentaR.setCantidad(Integer.parseInt(TCantidad.getText()));
            ObjTmpVentaR.setPrecio(ObjArticulo.getPrecio());
            ObjTmpVentaR.setSubtotal(Float.valueOf(LSubTotal.getText()));            
            facTVentasR.Nuevo_VentasR(ObjTmpVentaR);
            CargarTablaDetalles();
            LTotal.setText(String.valueOf( facTVentasR.getTotal()));

            LimpiarArticulo();
        } catch (SQLException ex) {
            Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        AgregarRegistro();
        
    }//GEN-LAST:event_BAgregarActionPerformed

    private void CargarTablaDetalles() {
        Conexion conexion;
        try {
            conexion = new Conexion();
            Connection conn = conexion.getConnection();
            Statement sta = conn.createStatement();
            String SQL = "select articulos_id, articulo, cantidad, precio, subtotal"
                    + "  from tmp_ventasr order by articulo";
            ResultSet registros = conn.createStatement().executeQuery(SQL);

            DefaultTableModel modoleAsignados = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int col) {
                    return false;  // hace que la jtable sea de lectura
                }
            };
            modoleAsignados.addColumn("Articulo_id");
            modoleAsignados.addColumn("Artículo");
            modoleAsignados.addColumn("Cantidad");
            modoleAsignados.addColumn("Precio");
            modoleAsignados.addColumn("SubTotal");
            while (registros.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = registros.getObject(i + 1);
                }
                modoleAsignados.addRow(fila);
            }
            JTablaDetalle.setModel(modoleAsignados);
            JTablaDetalle.getColumnModel().getColumn(0).setPreferredWidth(300);
            JTablaDetalle.getColumnModel().getColumn(1).setPreferredWidth(1600);
            JTablaDetalle.getColumnModel().getColumn(2).setPreferredWidth(300);
            JTablaDetalle.getColumnModel().getColumn(3).setPreferredWidth(300);
            JTablaDetalle.getColumnModel().getColumn(4).setPreferredWidth(300);
            if (JTablaDetalle.getRowCount() > 0) {
                BCancelar.setEnabled(true);
            } else {
                BCancelar.setEnabled(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        LTotal.setText(String.valueOf( facTVentasR.getTotal())); 
    }

    private void TCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCantidadKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            if ((car != '-') && (car != '+')) {
                evt.consume();
            }
        }

    }//GEN-LAST:event_TCantidadKeyTyped

    private void TCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCantidadKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (!TCantidad.getText().isEmpty()) {
                LSubTotal.setText(String.valueOf(Float.parseFloat(TCantidad.getText()) * Float.parseFloat(TPrecio.getText())));
                BAgregar.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_TCantidadKeyPressed

    private void BConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Esta Seguro de Registrar Venta", "Atención", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {          
            int nroventa= facTVentasR.NuevaVenta(TCliente.getText().trim());
            if (nroventa >0){
              JOptionPane.showMessageDialog(this, "Se Registro Venta Nro: " + nroventa, " Información", JOptionPane.INFORMATION_MESSAGE);  
              LimpiarArticulo();
              CargarTablaDetalles();
            }
        }
    }//GEN-LAST:event_BConfirmarActionPerformed

    private void TCodBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCodBarraKeyTyped
        
    }//GEN-LAST:event_TCodBarraKeyTyped

    private void TCodBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCodBarraKeyPressed
                
        
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
        {
             String strcodigo = TCodBarra.getText().toUpperCase().trim();  
             TCantidad.setText("1");
             TCantidad.requestFocusInWindow();
        try 
        {
            ObjArticulo =   facArticulo.ObtenerArticulos_CodBarra(strcodigo);
            TPrecio.setText(Float.toString(ObjArticulo.getPrecio()));
         
            
        } catch (SQLException ex) {
            Logger.getLogger(V_Ventas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
      
           LArticulo.setText(ObjArticulo.getArticulo());
           LMarca.setText(fMarca.ExisteMarca_Id(ObjArticulo.getMarca_id()));
           LRubro.setText(facRubros.ExisteRubro_Id(ObjArticulo.getRubro_id()));
           LDisponible.setText(String.valueOf(ObjArticulo.getCantidad()));
        }
       
        
    }//GEN-LAST:event_TCodBarraKeyPressed

    private void TCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCodBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCodBarraActionPerformed

    private void BAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BAgregarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            AgregarRegistro();
        }
    }//GEN-LAST:event_BAgregarKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BBArticulo;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BConfirmar;
    private javax.swing.JButton BSalir;
    private javax.swing.JTable JTablaDetalle;
    private javax.swing.JLabel LArticulo;
    private javax.swing.JLabel LDisponible;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LRubro;
    private javax.swing.JLabel LSubTotal;
    private javax.swing.JLabel LTotal;
    private javax.swing.JFormattedTextField TCantidad;
    private javax.swing.JTextField TCliente;
    private javax.swing.JTextField TCodBarra;
    private javax.swing.JTextField TPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
